language: generic

git:
  depth: 1

cache:
  directories:
    - $HOME/.stack/
    - $TRAVIS_BUILD_DIR/.stack-work/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - hvr-ghc
            - ubuntu-toolchain-r-test
          packages:
            - ghc-head

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:/opt/ghc/head/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --no-terminal build --only-dependencies --haddock --haddock-deps

install: true

script:
  - stack --no-terminal build --haddock --haddock-deps
  - ./boot.sh
