name: puellascript
version: 0.0.1
category: Language
synopsis: An experimental Haskell to JavaScript compiler.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/puellascript

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base >= 4.10 && < 5
  - ghc
  - ghc-paths

library:
  source-dirs: src
